# Sprites
SPRS=core.png gun.png ground.png cannonball.png spider.png selector_valid.png selector_invalid.png selector_select.png arrow_launcher.png arrow.png arrow_spider.png enemy_arrow.png flame_particle.png smoke_particle.png block_particle.png spider_bash.png spider_bow.png spider_bomb.png smasher.png smasher_top.png snake.png towers.png ui.png snake_bash.png number.png selector_cannot_place.png bat.png selector_refund.png bat_side_bash.png bat_low_bash.png shield.png spider_shield.png snake_shield.png spider_shield_static.png snake_shield_static.png bat_shield.png spear_launcher.png spider_spear.png spider_spear_bash.png bat_spear_bash.png bat_spear.png snake_spear.png snake_spear_bash.png next_wave.png menu.png help.png menu_select.png lose.png win.png

sprite:
	jot diffuse $(SPRS)
	cp images_diffuse.h ../src/images_diffuse.h
	cp images_diffuse.c ../src/images_diffuse.c